(lang dune 3.20)

(name aoc_2025)

(generate_opam_files true)

(package
 (name aoc_2025)
 (depends ocaml dune))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
